name: Build "turnip"

on: [pull_request, push, workflow_dispatch]


jobs:
  start_building_turnip:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo apt update
        sudo apt build-dep mesa -y
        sudo pip uninstall meson
        sudo pip install meson==1.1.0
        sudo apt install patchelf
    
    - name: Execute build script
      run: bash ./turnip_builder.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Upload meson and ninja logs for debugging
        path: |
          turnip_workdir/ninja_log
          turnip_workdir/mesa-main/build-quest-release/meson-logs/meson-log.txt
      
    - name: Release "turnip"
      uses: softprops/action-gh-release@v1
      with:
        body: QuestCraft Freedreno Build
        tag_name: Freedreno_QuestCraft_${{github.run_number}}
        name: Freedreno Release ${{github.run_number}} - QuestCraft
        files: |
           turnip_workdir/turnip.zip
